import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

//layout elements
import { Navbar } from "@/components/layout/navbar";

//font
import { Source_Code_Pro } from "next/font/google"
const sourceCodePro = Source_Code_Pro({ subsets: ["latin"] });

const geistSans = localFont({
  src: "../public/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Nicolò Spampatti | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${sourceCodePro.className}`}
      >
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
